### ISSUE TITLE
Inscrição Participante

### ISSUE THREAD

**Issue by berezanski** [uniarp/ext-admin#5]
Como participante preciso me inscrever nos eventos, para que possa participar dos mesmos; 

-O participante deve entrar na página de login do evento;
	-O login pode ser feito por RA ou CPF;
-Se o participante for acadêmico, deve fazer login com RA e uma senha que o sistema deverá gerar;
-O participante deve fazer login;
-O participante deve pressionar o botão inscrição  e vincular seu RA ou CPF ao evento disponível que vai aparecer para selecionar caso tenha mais que um evento em aberto através de uma lista (paginação);
-O participante deve pressionar o botão gravar para concluir a inscrição em tal evento;
Após isso será gerado um QrCode para que ele possa validar a entrada no evento.

![image](https://user-images.githubusercontent.com/55005876/75616052-a7c9dd80-5b2a-11ea-9d2b-5bc7a4811593.png)

**Comment by danconte72** [comment]
https://github.com/ionic-team/ionic-docs/blob/master/src/demos/api/list/index.html#L31

**Comment by GabrieSoares** [comment]
Precisa ajustar para pegar o código do participante logado, atualmente está fixo o participante 8.
