### ISSUE TITLE
Cadastro de Voluntario

### ISSUE THREAD

**Issue by GabrieSoares** [uniarp/ext-admin#8]
- Voluntários são pessoas que atuam num evento auxiliando o público e palestrantes. 
- Estes recebem um certificado específico além do de participação do evento.
- Na tela do evento o profissional da extensão escolhe a opção add voluntário.
- Abre uma janela modal.
- Exibe na tela os campos a serem preenchidos como obrigatório (ao informar o R.A o sistema verifica se já existe este cadastrado, se sim abre uma pop-up informando que este já está cadastrado, se não libera os demais campos para preenchimento, como, Nome, Telefone, E-mail). 
- Pressiona o botão gravar.
- Abre uma pop-up informando que o item foi gravado com sucesso.
- Pressiona o botão ok.
- Fecha a janela modal.

![image](https://user-images.githubusercontent.com/55005876/75615928-e9f21f80-5b28-11ea-8125-e858217c361b.png)

**Comment by Well-7** [comment]
![image](https://user-images.githubusercontent.com/55005876/75595307-90c3b680-5a6a-11ea-9986-5028157e77bf.png)

**Comment by Well-7** [comment]
Temos que melhorar (Implementar):
- [ ] Validador de CPF;
- [ ] Seletor de tipos curso (atualmente temos que digitar);
- [ ] Permitir salvar quando só os campos obrigatórios(*) forem preenchidos (atualmente não deixa, tem que preencher todos os campos para que se possa salvar);
